// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVFMyeG8EX5pP5phZs-O2L3UU5jw0INf4',
    appId: '1:159121462067:web:4772c33e0e50bafaf3e446',
    messagingSenderId: '159121462067',
    projectId: 'nexo-a87b7',
    authDomain: 'nexo-a87b7.firebaseapp.com',
    storageBucket: 'nexo-a87b7.firebasestorage.app',
    measurementId: 'G-TY79SQF2YD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChtHq0pixSPdkE_KkYVLbOp13nrSz3QhE',
    appId: '1:159121462067:android:faede3ee2cbe2689f3e446',
    messagingSenderId: '159121462067',
    projectId: 'nexo-a87b7',
    storageBucket: 'nexo-a87b7.firebasestorage.app',
  );
}
